//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEDM.ModeloDistribuidora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente : Persona
    {
        public Cliente()
        {
            this.FacVenta = new HashSet<FacVenta>();
        }
    
        public int IdCliente { get; set; }
        public string Ruc { get; set; }
    
        public virtual ICollection<FacVenta> FacVenta { get; set; }
    }
}
