//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEDM.ModeloDistribuidora
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacCompra
    {
        public int IdDetalleCompra { get; set; }
        public int CodPro { get; set; }
        public string DesPro { get; set; }
        public string MarPro { get; set; }
        public double CanPro { get; set; }
        public double PrecPro { get; set; }
        public double TotalPro { get; set; }
        public int FacCompraIdFacCompra { get; set; }
        public int ProductoIdProducto { get; set; }
    
        public virtual FacCompra FacCompra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
