//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEDM.ModeloDistribuidora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado : Persona
    {
        public Empleado()
        {
            this.FacCompra = new HashSet<FacCompra>();
        }
    
        public int IdEmplado { get; set; }
        public string Inss { get; set; }
        public string Cargo { get; set; }
        public string Carnet { get; set; }
        public System.DateTime FecIngreso { get; set; }
    
        public virtual ICollection<FacCompra> FacCompra { get; set; }
    }
}
