//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEDM.ModeloDistribuidora
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacCompra
    {
        public FacCompra()
        {
            this.DetalleFacCompra = new HashSet<DetalleFacCompra>();
        }
    
        public int IdFacCompra { get; set; }
        public System.DateTime Date { get; set; }
        public int Codigo { get; set; }
        public string NumFactura { get; set; }
        public double SubTotal { get; set; }
        public double IVA { get; set; }
        public double Total { get; set; }
        public int ProveedorIProveedor { get; set; }
        public int EmpleadoIdPersona { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual ICollection<DetalleFacCompra> DetalleFacCompra { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
