//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEDM.ModeloDistribuidora
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public Inventario()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int IdInventario { get; set; }
        public int Codigo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
    }
}
