//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModeloEDM.ModeloAcceso
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public Permiso()
        {
            this.AsignacionPermisos = new HashSet<AsignacionPermisos>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string CodPemiso { get; set; }
    
        public virtual ICollection<AsignacionPermisos> AsignacionPermisos { get; set; }
    }
}
